export const IMAGE_URL_CHANGE = 'IMAGE_URL_CHANGE';

export const ON_ROUTE_CHANGE = 'ON_ROUTE_CHANGE';
export const PROJECT_MAINPAGE = 'PROJECT_MAINPAGE';
export const APP_ROBOFRIEND= 'APP_ROBOFRIEND';
export const APP_SMARTBRAIN='APP_SMARTBRAIN';

export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
